util: Add missing include
This fixes the following kind of errors:

| In file included from .../core/hw-compatibility.c:12:
| .../include/util.h:210:23: error: unknown type name 'mode_t'
|   210 | int mkpath(char *dir, mode_t mode);
|       |                       ^~~~~~

This issue has been spotted when building against the musl libc.

Signed-off-by: Reto Schneider <reto.schneider@husqvarnagroup.com>